spring:
  application:
    name: task-management
  
  # datasource:
  #   url: jdbc:h2:mem:taskdb
  #   username: sa
  #   password: password
  #   driverClassName: org.h2.Driver
  datasource:
    url: jdbc:mysql://localhost:3306/task_management?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # jpa:
  #   database-platform: org.hibernate.dialect.H2Dialect
  #   hibernate:
  #     ddl-auto: update
  #   show-sql: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

# JWT Configuration
jwt:
  secret: 1ofhVAqY-5BXcUiJZ5fqVBwRLryN-AYHwgvnmloNBfotlrNwi0IzmQJWHs-io5d8zs9rsb81CWM8y1egHNm_OQ
  expiration: 86400000 # 24 hours

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html